### ISSUE TITLE
Pathogenic Incubator infinite food

### ISSUE THREAD

**Issue by Diabloshadow** [TheDaedalusCrew/Daedalus-of-Freedom#36]
#### Description of issue
Pathogenic Incubator has infinite virus food while a beaker with virus food is in it with .5 units

#### Difference between expected and actual behavior
Not supposed to have infinite virus food?

#### Steps to reproduce 
Fill a beaker and then put it in

#### Specific information for locating
Virology

#### Length of time in which bug has been known to occur
Unknown

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/TheDaedalusCrew/Daedalus-of-Freedom/issues)

**Comment by MyNameIsKodos** [comment]
I saw this today, too. So I can confirm that different players experience the bug.

**Comment by HiddenKn** [comment]
Can anyone make sure this has been fixed in the latest version?
