### ISSUE TITLE
Book "Standard Operating Procedure" not loading

### ISSUE THREAD

**Issue by MyNameIsKodos** [TheDaedalusCrew/Daedalus-of-Freedom#39]
#### Description of issue
When trying to open the book to read, it doesn't load properly.

As seen here:
![Resulting window seen here](https://puu.sh/yT13Q/6165963d51.png)

#### Difference between expected and actual behavior
Book should load, doesn't load.

#### Steps to reproduce 
Pick up book titled "Standard Operating Procedure" and activate it.

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: 8b097292d2b7690ef7c2846b2a64434cd8ec3d38 - master - 2018-01-01
Game ID: bSe-cW12
Current map: SEV Torch

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/TheDaedalusCrew/Daedalus-of-Freedom/issues)

**Comment by MyNameIsKodos** [comment]
Looks like multiple books have this issue, will work on a compiled list and add it.

**Comment by HiddenKn** [comment]
I believe none of the books work because the url's are not setup.
Do you want to fix the url's for this @MyNameIsKodos ? Point them to https://dofgaming.com/books.php?name=nameofthebookhere
Obviously replace the name with the name of the book.

**Comment by HiddenKn** [comment]
Books that were broken will now work assuming they have a page on the wiki.
